spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  #表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
  #配置静态资源根路径
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    # 默认路径
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    #模板格式
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #关闭缓存
    cache: false

#logback日志及输出
logging:
  config: classpath:logback-spring.xml
  file:
    path: D:\idea_workspace\SpringBoot_All\springboot_jpa_crud\logs
